# Database summary {.unnumbered}

```{r set}
#| message: false
#| warning: false
library(tidyverse)
```

```{r prep}
#| eval: false
read_tsv("db/guyaclim.tsv") |> 
  select(site, project, sensor, variable, id) |> 
  unique() |> 
  group_by(site, project, sensor, variable) |> 
  summarise(sensors = n()) |> 
  group_by(site, project, sensor, sensors) |> 
  summarise(variables = paste0(variable, collapse = ", ")) |> 
  write_tsv("db/vars.tsv")
read_tsv("db/guyaclim.tsv") |> 
  group_by(site, project, sensor, id, variable) |> 
  summarise(n = n()) |> 
  group_by(site, project, sensor, variable) |> 
  summarise(min = min(n), median = median(n), max = max(n)) |> 
  write_tsv("db/obs.tsv")
```

Available variables are:

```{r vars}
#| message: false
#| warning: false
read_tsv("db/vars.tsv") |> knitr::kable()
```

Number of observations are:

```{r obs}
#| message: false
#| warning: false
read_tsv("db/obs.tsv") |> 
  knitr::kable(format.args = list(big.mark = ",", scientific = FALSE))
```

```{r fig}
#| message: false
#| warning: false
#| fig-width: 10
#| fig-height: 10
#| cache: true
read_tsv("db/guyaclim.tsv") |> 
  filter(variable == "t_air") |> 
  ggplot(aes(date, value)) +
  geom_line(aes(group = id), alpha = .1) +
  theme_bw() +
  facet_wrap(~ site, nrow = 3) + 
  ylim(15, 40)
```
